Repository dnsimple/dnsimple-go, pull requests merged in 2020-05, with the labels that each got.

#90 Introduce request contexts
  CHANGELOG.md
  dnsimple/accounts.go
  dnsimple/accounts_test.go
  dnsimple/certificates.go
  dnsimple/certificates_test.go
  dnsimple/contacts.go
  dnsimple/contacts_test.go
  dnsimple/dnsimple.go
  dnsimple/dnsimple_test.go
  dnsimple/domains.go
  dnsimple/domains_collaborators.go
  dnsimple/domains_collaborators_test.go
  dnsimple/domains_delegation_signer_records.go
  dnsimple/domains_delegation_signer_records_test.go
  dnsimple/domains_dnssec.go
  dnsimple/domains_dnssec_test.go
  dnsimple/domains_email_forwards.go
  dnsimple/domains_email_forwards_test.go
  dnsimple/domains_pushes.go
  dnsimple/domains_pushes_test.go
  dnsimple/domains_test.go
  dnsimple/identity.go
  dnsimple/identity_test.go
  dnsimple/live_test.go
  dnsimple/oauth.go
  dnsimple/registrar.go
  dnsimple/registrar_auto_renewal.go
  dnsimple/registrar_auto_renewal_test.go
  dnsimple/registrar_delegation.go
  dnsimple/registrar_delegation_test.go
  dnsimple/registrar_test.go
  dnsimple/registrar_whois_privacy.go
  dnsimple/registrar_whois_privacy_test.go
  dnsimple/services.go
  dnsimple/services_domains.go
  dnsimple/services_domains_test.go
  dnsimple/services_test.go
  dnsimple/templates.go
  dnsimple/templates_domains.go
  dnsimple/templates_domains_test.go
  dnsimple/templates_records.go
  dnsimple/templates_records_test.go
  dnsimple/templates_test.go
  dnsimple/tlds.go
  dnsimple/tlds_test.go
  dnsimple/vanity_name_server.go
  dnsimple/vanity_name_servers_test.go
  dnsimple/webhooks.go
  dnsimple/webhooks_test.go
  dnsimple/zone_distributions.go
  dnsimple/zones.go
  dnsimple/zones_distributions_test.go
  dnsimple/zones_records.go
  dnsimple/zones_records_test.go
  dnsimple/zones_test.go
Labels: enhancement, ready-for-review

#92 Handle case where ZoneRecord name can be not present
  CHANGELOG.md
  dnsimple/dnsimple.go
  dnsimple/live_test.go
  dnsimple/zones_records.go
  dnsimple/zones_records_test.go
Labels: bug, ready-for-review

#93 Handle Go zero-value conflicts in sorting/filtering
  CHANGELOG.md
  README.md
  dnsimple/certificates_test.go
  dnsimple/contacts_test.go
  dnsimple/dnsimple.go
  dnsimple/domains.go
  dnsimple/domains_collaborators_test.go
  dnsimple/domains_delegation_signer_records_test.go
  dnsimple/domains_email_forwards_test.go
  dnsimple/domains_pushes_test.go
  dnsimple/domains_test.go
  dnsimple/services_test.go
  dnsimple/templates_records_test.go
  dnsimple/templates_test.go
  dnsimple/tlds_test.go
  dnsimple/zones.go
  dnsimple/zones_records.go
  dnsimple/zones_records_test.go
  dnsimple/zones_test.go
Labels: bug

#95 Provide convenient helper for authentication
  CHANGELOG.md
  README.md
  dnsimple/authentication.go
  dnsimple/authentication_test.go
Labels: enhancement, ready-for-review

#94 Implement client methods for Transfer API
  CHANGELOG.md
  dnsimple/registrar.go
  dnsimple/registrar_test.go
  fixtures.http/api/cancelDomainTransfer/success.http
  fixtures.http/api/getDomainTransfer/success.http
Labels: enhancement

#97 Introduce account membership events
  dnsimple/accounts.go
  dnsimple/webhook/events.go
  dnsimple/webhook/events_test.go
  fixtures.http/webhooks/account.remove_user/example.http
  fixtures.http/webhooks/account.user_invitation_accept/example.http
  fixtures.http/webhooks/account.user_invitation_revoke/example.http
  fixtures.http/webhooks/account.user_invite/example.http
  fixtures.http/webhooks/account.user_remove/example.http
  fixtures.http/webhooks/account_invitation.create/example.http
Labels: enhancement, ready-for-review
